CREATE TABLE addresses (
    id SERIAL PRIMARY KEY,
    wkt TEXT,
    address_id BIGINT NOT NULL,
    road_id BIGINT,
    full_address_number VARCHAR(100),
    full_road_name VARCHAR(255),
    full_address VARCHAR(400) NOT NULL,
    territorial_authority VARCHAR(100),
    unit VARCHAR(50),
    address_number INT,
    address_number_suffix VARCHAR(10),
    address_number_high INT,
    road_name VARCHAR(255),
    road_name_type VARCHAR(100),
    road_name_suffix VARCHAR(50),
    suburb_locality VARCHAR(100),
    town_city VARCHAR(100),
    is_land VARCHAR(5),
    address_lifecycle VARCHAR(50),
    full_road_name_ascii VARCHAR(255),
    full_address_ascii VARCHAR(400),
    territorial_authority_ascii VARCHAR(100),
    road_name_ascii VARCHAR(255),
    suburb_locality_ascii VARCHAR(100),
    town_city_ascii VARCHAR(100),
    shape_x DECIMAL(20, 8),
    shape_y DECIMAL(20, 8),
    shape GEOMETRY(Point, 4326)
);
