CREATE TABLE addresses (
    id SERIAL PRIMARY KEY,
    source_address_id INT NOT NULL,
    source_dataset VARCHAR(20),
    source_change_id INT,
    full_address_number VARCHAR(100) NOT NULL,
    full_road_name VARCHAR(255) NOT NULL,
    full_address VARCHAR(400) NOT NULL,
    address_number_prefix VARCHAR(26),
    address_number INT NOT NULL,
    address_number_suffix VARCHAR(10),
    road_name VARCHAR(100) NOT NULL,
    road_name_type VARCHAR(100),
    suburb_locality VARCHAR(80),
    town_city VARCHAR(80),
    xcoord DECIMAL(20, 8),
    ycoord DECIMAL(20, 8),
    road_name_ascii VARCHAR(255),
    suburb_locality_ascii VARCHAR(100),
    town_city_ascii VARCHAR(100),
    full_road_name_ascii VARCHAR(255),
    full_address_ascii VARCHAR(255),
    shape GEOMETRY(Point, 4326),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
